### ISSUE TITLE
failed calulation on the InductionMachines examples

### ISSUE THREAD

**Issue by ghost** [christiankral/HanserModelica#12] opened 2021-02-12 07:57 UTC
I tried to simulate the models with the induction machines (OpenModelica, 1.16.2) and had some problems to get a solution. The compiling process works fine but afterwards the calculation progress first shows 1% and then immediately jups back to 0% and never changes again. I stopped the calculation after a few minutes.
I tried several models out of the other packages and all worked well. Also the models 'IMC_Steinmetz', 'IMC_Inverter1' and 'IMC_Inverter2' had no problems.

**Comment by christiankral** [comment] 2021-02-17 09:01
I am using a recent "Nightly" version of OpenModelica and I tested some examples that just worked OK. Could you please more precisely point out one example which did not work, so that we can start the discussion from there.

Could you also please state what operating system you are using, as I recently experienced some [issue with the Windows](https://trac.openmodelica.org/OpenModelica/ticket/6348) release of OpenModelica 1.16.

**Comment by ghost** [comment] 2021-02-17 09:28
One of the examples not working is the HanserModelica.InductionMachines.IMS_Characteristics1.
I am using a windows 10 64bit version. The issue you reportet in the linked post seems to be excatly the one I'm experiencing.

Edit: I now installed the OpenModelica v1.15.0-dev-48-g3656b9544 and all the models are working. So like you pointed out in the post you linked, an older version of OpenModelica provides a first solution.

**Comment by christiankral** [comment] 2021-02-21 16:36
The example `HanserModelica.InductionMachines.IMS_Characteristics1` simulates OK under Linux but **not** in the Windows version of OpenModelica 1.16.0. As a workaround you can enable the old frontend in Windows:

![image](https://user-images.githubusercontent.com/4184218/108631628-fc1c4a80-746a-11eb-80ea-89f1ccfd22c2.png)

For the new frontend we have to wait until [OpenModelica issue #6348](https://trac.openmodelica.org/OpenModelica/ticket/6348) is resolved.

**Comment by casella** [comment] 2021-02-21 17:14
@christiankral, I tried to use the old frontend in Windows, but I got the same problem. We'll try to figure out what is going on there.

**Comment by christiankral** [comment] 2021-02-28 17:02
The issue is fixed now. If you want to benefit from the bug fix you have to install a Nightly version or wait for OpenModelica 1.17. The bug fix is **not** backported to OpenModelica 1.16.4 and 1.16.5.

**Closed as completed by christiankral** 2021-02-28 17:02 UTC

**Comment by casella** [comment] 2021-02-28 21:52
BTW 1.17.0-dev.beta2 is out now
